
/**
 * @description 常量
 * **/
class CommonConstants {
  static readonly NAME: string = "AUIAICall";
  static readonly FULL_LENGTH: string = '100%';
  //Divider strokeWidth.
  static readonly STROKE_WIDTH: number = 2;
  //Animation duration.
  static readonly ANIMATION_DURATION: number = 500;
  static readonly COLUMN_HEIGHT: number = 100;
  static readonly SET_INTERVAL_TIME: number = 100;
  static readonly OPACITY_FALSE: number = 0;
  static readonly OPACITY_TRUE: number = 1;
  static readonly COLUMN_WIDTH: number = 5;
  static readonly BLANK_COLUMN: number = 20;

  static readonly AGENT_XC_COMPONENT: string = 'Agent_XComponent';
  static readonly LOCAL_XC_COMPONENT: string = 'Local_XComponent';

}

export { CommonConstants }