class RouterConstants {
  static readonly MAIN_PAGE: string = 'main_page';
  static readonly AUDIO_CALL_PAGE: string = 'audio_call_page';
  static readonly AVATAR_CALL_PAGE: string = 'avatar_call_page';
  static readonly VISION_CALL_PAGE = 'vision_call_page';
  static readonly VIDEO_CALL_PAGE: string = 'video_call_page';
  static readonly OUTBOUND_PAGE = 'outbound_page'
  static readonly OUTBOUND_CALLING_PAGE: string = 'outbound_calling_page';
  static readonly INBOUND_PAGE = 'inbound_page'



  static readonly VOICE_STYLE_DIALOG: string = 'voice_style_dialog';

}

export { RouterConstants }