
platform :ios, '10.0'

workspace 'AUIAICallExample'

AlivcSDK='AliVCSDK_ARTC'

target 'Example' do

  pod "#{AlivcSDK}", '~> 6.21.0'
  pod 'AliVCInteractionMessage', '~> 1.5.0'
  pod "ARTCAICallKit/Chatbot", '~> 2.0.0'

  pod 'MJRefresh', :modular_headers => true
  pod 'AUIFoundation', :path => '../AUIBaseKits/AUIFoundation/', :modular_headers => true
  pod "AUIAICall/Demo", :path => '../'

end
