
platform :ios, '11.0'

workspace 'AUIAICallExample'

AlivcSDK='AliVCSDK_ARTC'

target 'Example' do

  pod "#{AlivcSDK}", '~> 7.4.0'
  pod 'AliVCInteractionMessage', '~> 1.8.0'
  pod "ARTCAICallKit/Chatbot", '~> 2.7.0'

  pod 'MJRefresh', :modular_headers => true
  pod 'SDWebImage', :modular_headers => true
  pod 'AliyunOSSiOS', :modular_headers => true
  pod 'AUIFoundation', :path => '../AUIBaseKits/AUIFoundation/', :modular_headers => true
  pod "AUIAICall/Demo", :path => '../'

end
