server:
  port: 8080

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss
    default-property-inclusion: non_null

# 参考 https://help.aliyun.com/zh/ims/user-guide/app-server-reference, 不需要的配置保留*******即可
biz:
  # 阿里云AK、SK，参考 https://help.aliyun.com/zh/ram/user-guide/create-an-accesskey-pair。 创建RAM用户时，最小权限为AliyunICEFullAccess
  openapi:
    # 调用generateMessageToken 获取chatBot token时需要配置
    # 调用describeAIAgentInstance 获取智能体信息时需要配置
    access:
      key: "*******"
      secret: "*******"

  # 实时音视频应用ID和AppKey，通话场景下需要配置
  live_mic:
    app_id: "*******"
    app_key: "*******"

http:
  cors:
    host: "*"