package com.aliyun.auikits.aiagent.util;

public interface IMsgTypeDef {
    int MSG_TYPE_AI_AGENT_ERROR_NOTIFY = 1000;
    int MSG_TYPE_AI_AGENT_STATE_CHANGE = 1001;
    int MSG_TYPE_ROBOT_TEXT = 1002;
    int MSG_TYPE_USER_ASR_TEXT = 1003;
    int MSG_TYPE_SWITCH_VOICE_INTERRUPT_RESULT = 1004;
    int MSG_TYPE_SWITCH_VOICE_ID_RESULT = 1005;
    int MSG_TYPE_RTC_TOKEN_REFRESH_RESULT = 1006;
    int MSG_TYPE_PUSH_TO_TALK_ENABLE_RESULT = 1007;
    int MSG_TYPE_VOICE_PRINT_ENABLE_RESULT = 1008;
    int MSG_TYPE_DELETE_PRINT_ENABLE_RESULT = 1009;
    int MSG_TYPE_AI_AGENT_LEAVE_NOTIFY = 1010;
    int MSG_TYPE_AI_AGENT_CUSTOM_MESSAGE_NOTIFY = 1011;

    int MSG_TYPE_STOP_AI_AGENT = 1100;
    int MSG_TYPE_INTERRUPT_ROBOT_SPEAK = 1101;
    int MSG_TYPE_SWITCH_VOICE_INTERRUPT = 1102;
    int MSG_TYPE_SWITCH_VOICE_ID = 1103;
    int MSG_TYPE_REFRESH_RTC_TOKEN = 1104;
    int MSG_TYPE_ENABLE_PUSH_TO_TALK = 1105;
    int MSG_TYPE_START_PUSH_TO_TALK = 1106;
    int MSG_TYPE_FINISH_PUSH_TO_TALK = 1107;
    int MSG_TYPE_CANCEL_PUSH_TO_TALK = 1108;
    int MSG_TYPE_ENABLE_VOICE_PRINT = 1109;
    int MSG_TYPE_CLEAR_VOICE_PRINT = 1110;

    interface ROBOT_STATE {
        int ROBOT_STATE_LISTENING = 1;
        int ROBOT_STATE_THINKING = 2;
        int ROBOT_STATE_SPEAKING = 3;
    }

    interface AI_AGENT_ERROR_CODE {
        int AI_AGENT_CONCURRENT_ROUTES_EXHAUSTED = 4001;
        int AI_AGENT_AUDIO_SUBSCRIBE_FAILED = 4004;
        int AI_AGENT_ASR_UNAVAILABLE = 4005;
        int AI_AGENT_AVATAR_AGENT_UNAVAILABLE = 4006;
    }
}
